## Global Stats

In [1]:
import requests
import pandas as pd
pd.set_option("display.max_rows", 500)

In [3]:
r = requests.get('https://api.thevirustracker.com/free-api?global=stats').json()

In [4]:
r

{'results': [{'total_cases': 3808488,
   'total_recovered': 1287600,
   'total_unresolved': 2039891,
   'total_deaths': 263877,
   'total_new_cases_today': 83970,
   'total_new_deaths_today': 5851,
   'total_active_cases': 2257011,
   'total_serious_cases': 48242,
   'total_affected_countries': 212,
   'source': {'url': 'https://thevirustracker.com/'}}],
 'stat': 'ok'}

In [8]:
r['results'][0]

{'total_cases': 3808488,
 'total_recovered': 1287600,
 'total_unresolved': 2039891,
 'total_deaths': 263877,
 'total_new_cases_today': 83970,
 'total_new_deaths_today': 5851,
 'total_active_cases': 2257011,
 'total_serious_cases': 48242,
 'total_affected_countries': 212,
 'source': {'url': 'https://thevirustracker.com/'}}

## Country

In [9]:
req = requests.get("https://api.thevirustracker.com/free-api?countryTotal=IN").json()

In [14]:
req['countrydata'][0]

{'info': {'ourid': 72,
  'title': 'India',
  'code': 'IN',
  'source': 'https://thevirustracker.com/india-coronavirus-information-in'},
 'total_cases': 52987,
 'total_recovered': 15331,
 'total_unresolved': 0,
 'total_deaths': 1785,
 'total_new_cases_today': 3587,
 'total_new_deaths_today': 92,
 'total_active_cases': 35871,
 'total_serious_cases': 0,
 'total_danger_rank': 14}

In [8]:
r = requests.get("https://api.thevirustracker.com/free-api?countryTotals=ALL").json()
r.keys()

dict_keys(['sitedata', 'countryitems'])

In [5]:
r['countryitems'][0]

{'1': {'ourid': 1,
  'title': 'Afghanistan',
  'code': 'AF',
  'source': 'https://thevirustracker.com/afghanistan-coronavirus-information-af',
  'total_cases': 3563,
  'total_recovered': 468,
  'total_unresolved': 0,
  'total_deaths': 106,
  'total_new_cases_today': 171,
  'total_new_deaths_today': 2,
  'total_active_cases': 2989,
  'total_serious_cases': 7},
 '2': {'ourid': 2,
  'title': 'Albania',
  'code': 'AL',
  'source': 'https://thevirustracker.com/albania-coronavirus-information-al',
  'total_cases': 842,
  'total_recovered': 605,
  'total_unresolved': 0,
  'total_deaths': 31,
  'total_new_cases_today': 10,
  'total_new_deaths_today': 0,
  'total_active_cases': 206,
  'total_serious_cases': 7},
 '3': {'ourid': 3,
  'title': 'Algeria',
  'code': 'DZ',
  'source': 'https://thevirustracker.com/algeria-coronavirus-information-dz',
  'total_cases': 4997,
  'total_recovered': 2197,
  'total_unresolved': 0,
  'total_deaths': 476,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 2324,
  'total_serious_cases': 22},
 '4': {'ourid': 4,
  'title': 'Angola',
  'code': 'AO',
  'source': 'https://thevirustracker.com/angola-coronavirus-information-ao',
  'total_cases': 36,
  'total_recovered': 11,
  'total_unresolved': 0,
  'total_deaths': 2,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 23,
  'total_serious_cases': 0},
 '5': {'ourid': 5,
  'title': 'Argentina',
  'code': 'AR',
  'source': 'https://thevirustracker.com/argentina-coronavirus-information-ar',
  'total_cases': 5208,
  'total_recovered': 1524,
  'total_unresolved': 0,
  'total_deaths': 273,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 3411,
  'total_serious_cases': 148},
 '6': {'ourid': 6,
  'title': 'Armenia',
  'code': 'AM',
  'source': 'https://thevirustracker.com/armenia-coronavirus-information-am',
  'total_cases': 2884,
  'total_recovered': 1185,
  'total_unresolved': 0,
  'total_deaths': 42,
  'total_new_cases_today': 102,
  'total_new_deaths_today': 2,
  'total_active_cases': 1657,
  'total_serious_cases': 10},
 '7': {'ourid': 7,
  'title': 'Australia',
  'code': 'AU',
  'source': 'https://thevirustracker.com/australia-coronavirus-information-au',
  'total_cases': 6896,
  'total_recovered': 6040,
  'total_unresolved': 0,
  'total_deaths': 97,
  'total_new_cases_today': 21,
  'total_new_deaths_today': 0,
  'total_active_cases': 759,
  'total_serious_cases': 23},
 '8': {'ourid': 8,
  'title': 'Austria',
  'code': 'AT',
  'source': 'https://thevirustracker.com/austria-coronavirus-information-at',
  'total_cases': 15752,
  'total_recovered': 13698,
  'total_unresolved': 0,
  'total_deaths': 609,
  'total_new_cases_today': 68,
  'total_new_deaths_today': 1,
  'total_active_cases': 1445,
  'total_serious_cases': 92},
 '9': {'ourid': 9,
  'title': 'Azerbaijan',
  'code': 'AZ',
  'source': 'https://thevirustracker.com/azerbaijan-coronavirus-information-az',
  'total_cases': 2127,
  'total_recovered': 1536,
  'total_unresolved': 0,
  'total_deaths': 28,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 563,
  'total_serious_cases': 18},
 '10': {'ourid': 10,
  'title': 'Bahamas',
  'code': 'BS',
  'source': 'https://thevirustracker.com/bahamas-coronavirus-information-bs',
  'total_cases': 92,
  'total_recovered': 26,
  'total_unresolved': 0,
  'total_deaths': 11,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 55,
  'total_serious_cases': 1},
 '11': {'ourid': 11,
  'title': 'Bangladesh',
  'code': 'BD',
  'source': 'https://thevirustracker.com/bangladesh-coronavirus-information-bd',
  'total_cases': 12425,
  'total_recovered': 1910,
  'total_unresolved': 0,
  'total_deaths': 186,
  'total_new_cases_today': 706,
  'total_new_deaths_today': 0,
  'total_active_cases': 10329,
  'total_serious_cases': 1},
 '12': {'ourid': 12,
  'title': 'Belarus',
  'code': 'BY',
  'source': 'https://thevirustracker.com/belarus-coronavirus-information-by',
  'total_cases': 19255,
  'total_recovered': 4388,
  'total_unresolved': 0,
  'total_deaths': 112,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 14755,
  'total_serious_cases': 92},
 '13': {'ourid': 13,
  'title': 'Belgium',
  'code': 'BE',
  'source': 'https://thevirustracker.com/belgium-coronavirus-information-be',
  'total_cases': 51420,
  'total_recovered': 12980,
  'total_unresolved': 0,
  'total_deaths': 8415,
  'total_new_cases_today': 639,
  'total_new_deaths_today': 76,
  'total_active_cases': 30025,
  'total_serious_cases': 538},
 '14': {'ourid': 14,
  'title': 'Belize',
  'code': 'BZ',
  'source': 'https://thevirustracker.com/belize-coronavirus-information-bz',
  'total_cases': 18,
  'total_recovered': 14,
  'total_unresolved': 0,
  'total_deaths': 2,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 2,
  'total_serious_cases': 1},
 '15': {'ourid': 15,
  'title': 'Benin',
  'code': 'BJ',
  'source': 'https://thevirustracker.com/benin-coronavirus-information-bj',
  'total_cases': 140,
  'total_recovered': 53,
  'total_unresolved': 0,
  'total_deaths': 2,
  'total_new_cases_today': 44,
  'total_new_deaths_today': 0,
  'total_active_cases': 85,
  'total_serious_cases': 0},
 '16': {'ourid': 16,
  'title': 'Bhutan',
  'code': 'BT',
  'source': 'https://thevirustracker.com/bhutan-coronavirus-information-bt',
  'total_cases': 7,
  'total_recovered': 5,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 2,
  'total_serious_cases': 0},
 '17': {'ourid': 17,
  'title': 'Bolivia',
  'code': 'BO',
  'source': 'https://thevirustracker.com/bolivia-coronavirus-information-bo',
  'total_cases': 1886,
  'total_recovered': 198,
  'total_unresolved': 0,
  'total_deaths': 91,
  'total_new_cases_today': 84,
  'total_new_deaths_today': 5,
  'total_active_cases': 1597,
  'total_serious_cases': 3},
 '18': {'ourid': 18,
  'title': 'Bosnia and Herzegovina',
  'code': 'BA',
  'source': 'https://thevirustracker.com/bosnia-and-herzegovina-coronavirus-information-ba',
  'total_cases': 2027,
  'total_recovered': 954,
  'total_unresolved': 0,
  'total_deaths': 90,
  'total_new_cases_today': 40,
  'total_new_deaths_today': 4,
  'total_active_cases': 983,
  'total_serious_cases': 4},
 '19': {'ourid': 19,
  'title': 'Botswana',
  'code': 'BW',
  'source': 'https://thevirustracker.com/botswana-coronavirus-information-bw',
  'total_cases': 23,
  'total_recovered': 8,
  'total_unresolved': 0,
  'total_deaths': 1,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 14,
  'total_serious_cases': 0},
 '20': {'ourid': 20,
  'title': 'Brazil',
  'code': 'BR',
  'source': 'https://thevirustracker.com/brazil-coronavirus-information-br',
  'total_cases': 126611,
  'total_recovered': 51370,
  'total_unresolved': 0,
  'total_deaths': 8588,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 66653,
  'total_serious_cases': 8318},
 '21': {'ourid': 21,
  'title': 'Brunei Darussalam',
  'code': 'BN',
  'source': 'https://thevirustracker.com/brunei-darussalam-coronavirus-information-bn',
  'total_cases': 141,
  'total_recovered': 131,
  'total_unresolved': 0,
  'total_deaths': 1,
  'total_new_cases_today': 2,
  'total_new_deaths_today': 0,
  'total_active_cases': 9,
  'total_serious_cases': 2},
 '22': {'ourid': 22,
  'title': 'Bulgaria',
  'code': 'BG',
  'source': 'https://thevirustracker.com/bulgaria-coronavirus-information-bg',
  'total_cases': 1811,
  'total_recovered': 384,
  'total_unresolved': 0,
  'total_deaths': 84,
  'total_new_cases_today': 33,
  'total_new_deaths_today': 0,
  'total_active_cases': 1343,
  'total_serious_cases': 38},
 '23': {'ourid': 23,
  'title': 'Burkina Faso',
  'code': 'BF',
  'source': 'https://thevirustracker.com/burkina-faso-coronavirus-information-bf',
  'total_cases': 729,
  'total_recovered': 555,
  'total_unresolved': 0,
  'total_deaths': 48,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 126,
  'total_serious_cases': 0},
 '24': {'ourid': 24,
  'title': 'Burundi',
  'code': 'BI',
  'source': 'https://thevirustracker.com/burundi-coronavirus-information-bi',
  'total_cases': 15,
  'total_recovered': 7,
  'total_unresolved': 0,
  'total_deaths': 1,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 7,
  'total_serious_cases': 0},
 '25': {'ourid': 25,
  'title': 'Cambodia',
  'code': 'KH',
  'source': 'https://thevirustracker.com/cambodia-coronavirus-information-kh',
  'total_cases': 122,
  'total_recovered': 120,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 2,
  'total_serious_cases': 1},
 '26': {'ourid': 26,
  'title': 'Cameroon',
  'code': 'CM',
  'source': 'https://thevirustracker.com/cameroon-coronavirus-information-cm',
  'total_cases': 2267,
  'total_recovered': 1002,
  'total_unresolved': 0,
  'total_deaths': 108,
  'total_new_cases_today': 2,
  'total_new_deaths_today': 0,
  'total_active_cases': 1157,
  'total_serious_cases': 12},
 '27': {'ourid': 27,
  'title': 'Canada',
  'code': 'CA',
  'source': 'https://thevirustracker.com/canada-coronavirus-information-ca',
  'total_cases': 63496,
  'total_recovered': 28171,
  'total_unresolved': 0,
  'total_deaths': 4232,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 31093,
  'total_serious_cases': 502},
 '28': {'ourid': 28,
  'title': 'Central African Republic',
  'code': 'CF',
  'source': 'https://thevirustracker.com/central-african-republic-coronavirus-information-cf',
  'total_cases': 1,
  'total_recovered': 0,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 0,
  'total_serious_cases': 0},
 '29': {'ourid': 29,
  'title': 'Chad',
  'code': 'TD',
  'source': 'https://thevirustracker.com/chad-coronavirus-information-td',
  'total_cases': 170,
  'total_recovered': 43,
  'total_unresolved': 0,
  'total_deaths': 17,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 110,
  'total_serious_cases': 0},
 '30': {'ourid': 30,
  'title': 'Chile',
  'code': 'CL',
  'source': 'https://thevirustracker.com/chile-coronavirus-information-cl',
  'total_cases': 23048,
  'total_recovered': 11189,
  'total_unresolved': 0,
  'total_deaths': 281,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 11578,
  'total_serious_cases': 470},
 '31': {'ourid': 31,
  'title': 'China',
  'code': 'CN',
  'source': 'https://thevirustracker.com/china-coronavirus-information-cn',
  'total_cases': 82885,
  'total_recovered': 77957,
  'total_unresolved': 0,
  'total_deaths': 4633,
  'total_new_cases_today': 2,
  'total_new_deaths_today': 0,
  'total_active_cases': 295,
  'total_serious_cases': 23},
 '32': {'ourid': 32,
  'title': 'Colombia',
  'code': 'CO',
  'source': 'https://thevirustracker.com/colombia-coronavirus-information-co',
  'total_cases': 8959,
  'total_recovered': 2148,
  'total_unresolved': 0,
  'total_deaths': 397,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 6414,
  'total_serious_cases': 123},
 '33': {'ourid': 33,
  'title': 'Congo',
  'code': 'CG',
  'source': 'https://thevirustracker.com/congo-coronavirus-information-cg',
  'total_cases': 264,
  'total_recovered': 30,
  'total_unresolved': 0,
  'total_deaths': 10,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 224,
  'total_serious_cases': 0},
 '34': {'ourid': 34,
  'title': 'Democratic Republic of Congo',
  'code': 'CD',
  'source': 'https://thevirustracker.com/democratic-republic-of-congo-coronavirus-information-cd',
  'total_cases': 0,
  'total_recovered': 0,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 0,
  'total_serious_cases': 0},
 '35': {'ourid': 35,
  'title': 'Costa Rica',
  'code': 'CR',
  'source': 'https://thevirustracker.com/costa-rica-coronavirus-information-cr',
  'total_cases': 761,
  'total_recovered': 428,
  'total_unresolved': 0,
  'total_deaths': 6,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 327,
  'total_serious_cases': 5},
 '36': {'ourid': 36,
  'title': 'Ivory Coast',
  'code': 'CI',
  'source': 'https://thevirustracker.com/ivory-coast-coronavirus-information-ci',
  'total_cases': 1516,
  'total_recovered': 721,
  'total_unresolved': 0,
  'total_deaths': 18,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 777,
  'total_serious_cases': 0},
 '37': {'ourid': 37,
  'title': 'Croatia',
  'code': 'HR',
  'source': 'https://thevirustracker.com/croatia-coronavirus-information-hr',
  'total_cases': 2119,
  'total_recovered': 1601,
  'total_unresolved': 0,
  'total_deaths': 85,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 433,
  'total_serious_cases': 14},
 '38': {'ourid': 38,
  'title': 'Cuba',
  'code': 'CU',
  'source': 'https://thevirustracker.com/cuba-coronavirus-information-cu',
  'total_cases': 1703,
  'total_recovered': 1001,
  'total_unresolved': 0,
  'total_deaths': 69,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 633,
  'total_serious_cases': 14},
 '39': {'ourid': 39,
  'title': 'Cyprus',
  'code': 'CY',
  'source': 'https://thevirustracker.com/cyprus-coronavirus-information-cy',
  'total_cases': 883,
  'total_recovered': 296,
  'total_unresolved': 0,
  'total_deaths': 15,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 572,
  'total_serious_cases': 15},
 '40': {'ourid': 40,
  'title': 'Czechia',
  'code': 'CZ',
  'source': 'https://thevirustracker.com/czechia-coronavirus-information-cz',
  'total_cases': 7979,
  'total_recovered': 4214,
  'total_unresolved': 0,
  'total_deaths': 263,
  'total_new_cases_today': 5,
  'total_new_deaths_today': 1,
  'total_active_cases': 3502,
  'total_serious_cases': 52},
 '41': {'ourid': 41,
  'title': 'Denmark',
  'code': 'DK',
  'source': 'https://thevirustracker.com/denmark-coronavirus-information-dk',
  'total_cases': 10083,
  'total_recovered': 7493,
  'total_unresolved': 0,
  'total_deaths': 506,
  'total_new_cases_today': 145,
  'total_new_deaths_today': 0,
  'total_active_cases': 2084,
  'total_serious_cases': 46},
 '42': {'ourid': 42,
  'title': 'Djibouti',
  'code': 'DJ',
  'source': 'https://thevirustracker.com/djibouti-coronavirus-information-dj',
  'total_cases': 1124,
  'total_recovered': 755,
  'total_unresolved': 0,
  'total_deaths': 3,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 366,
  'total_serious_cases': 0},
 '43': {'ourid': 43,
  'title': 'Dominican Republic',
  'code': 'DO',
  'source': 'https://thevirustracker.com/dominican-republic-coronavirus-information-do',
  'total_cases': 8807,
  'total_recovered': 1960,
  'total_unresolved': 0,
  'total_deaths': 362,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 6485,
  'total_serious_cases': 144},
 '44': {'ourid': 44,
  'title': 'Ecuador',
  'code': 'EC',
  'source': 'https://thevirustracker.com/ecuador-coronavirus-information-ec',
  'total_cases': 29420,
  'total_recovered': 3433,
  'total_unresolved': 0,
  'total_deaths': 1618,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 24369,
  'total_serious_cases': 156},
 '45': {'ourid': 45,
  'title': 'Egypt',
  'code': 'EG',
  'source': 'https://thevirustracker.com/egypt-coronavirus-information-eg',
  'total_cases': 7588,
  'total_recovered': 1815,
  'total_unresolved': 0,
  'total_deaths': 469,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 5304,
  'total_serious_cases': 0},
 '46': {'ourid': 46,
  'title': 'El Salvador',
  'code': 'SV',
  'source': 'https://thevirustracker.com/el-salvador-coronavirus-information-sv',
  'total_cases': 695,
  'total_recovered': 245,
  'total_unresolved': 0,
  'total_deaths': 15,
  'total_new_cases_today': 62,
  'total_new_deaths_today': 0,
  'total_active_cases': 435,
  'total_serious_cases': 4},
 '47': {'ourid': 47,
  'title': 'Equatorial Guinea',
  'code': 'GQ',
  'source': 'https://thevirustracker.com/equatorial-guinea-coronavirus-information-gq',
  'total_cases': 439,
  'total_recovered': 13,
  'total_unresolved': 0,
  'total_deaths': 4,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 422,
  'total_serious_cases': 0},
 '48': {'ourid': 48,
  'title': 'Eritrea',
  'code': 'ER',
  'source': 'https://thevirustracker.com/eritrea-coronavirus-information-er',
  'total_cases': 39,
  'total_recovered': 30,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 9,
  'total_serious_cases': 0},
 '49': {'ourid': 49,
  'title': 'Estonia',
  'code': 'EE',
  'source': 'https://thevirustracker.com/estonia-coronavirus-information-ee',
  'total_cases': 1720,
  'total_recovered': 273,
  'total_unresolved': 0,
  'total_deaths': 56,
  'total_new_cases_today': 7,
  'total_new_deaths_today': 1,
  'total_active_cases': 1391,
  'total_serious_cases': 4},
 '50': {'ourid': 50,
  'title': 'Ethiopia',
  'code': 'ET',
  'source': 'https://thevirustracker.com/ethiopia-coronavirus-information-et',
  'total_cases': 187,
  'total_recovered': 93,
  'total_unresolved': 0,
  'total_deaths': 4,
  'total_new_cases_today': 25,
  'total_new_deaths_today': 0,
  'total_active_cases': 90,
  'total_serious_cases': 1},
 '51': {'ourid': 51,
  'title': 'Falkland Islands',
  'code': 'FK',
  'source': 'https://thevirustracker.com/falkland-islands-coronavirus-information-fk',
  'total_cases': 13,
  'total_recovered': 11,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 2,
  'total_serious_cases': 0},
 '52': {'ourid': 52,
  'title': 'Fiji',
  'code': 'FJ',
  'source': 'https://thevirustracker.com/fiji-coronavirus-information-fj',
  'total_cases': 18,
  'total_recovered': 14,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 4,
  'total_serious_cases': 0},
 '53': {'ourid': 53,
  'title': 'Finland',
  'code': 'FI',
  'source': 'https://thevirustracker.com/finland-coronavirus-information-fi',
  'total_cases': 5673,
  'total_recovered': 3500,
  'total_unresolved': 0,
  'total_deaths': 255,
  'total_new_cases_today': 100,
  'total_new_deaths_today': 3,
  'total_active_cases': 1918,
  'total_serious_cases': 44},
 '54': {'ourid': 54,
  'title': 'France',
  'code': 'FR',
  'source': 'https://thevirustracker.com/france-coronavirus-information-fr',
  'total_cases': 174191,
  'total_recovered': 53972,
  'total_unresolved': 0,
  'total_deaths': 25809,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 94410,
  'total_serious_cases': 3147},
 '55': {'ourid': 55,
  'title': 'French Guiana',
  'code': 'GF',
  'source': 'https://thevirustracker.com/french-guiana-coronavirus-information-gf',
  'total_cases': 138,
  'total_recovered': 112,
  'total_unresolved': 0,
  'total_deaths': 1,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 25,
  'total_serious_cases': 0},
 '56': {'ourid': 56,
  'title': 'French Southern Territories',
  'code': 'TF',
  'source': 'https://thevirustracker.com/french-southern-territories-coronavirus-information-tf',
  'total_cases': 0,
  'total_recovered': 0,
  'total_unresolved': 0,
  'total_deaths': 0,
  'total_new_cases_today': 0,
  'total_new_deaths_today': 0,
  'total_active_cases': 0,

In [ ]:
data_dict = r['countryitems'][0].copy()
data_dict['stat']
del data_dict['stat']

In [17]:
final = dict(
    country = list(),
    code = list(),
    confirmed = list(),
    active = list(),
    recovered = list(),
    deaths = list(),
    cases_today = list(),
    deaths_today = list(),
    serious = list()
)

In [18]:
for k, v in data_dict.items():
    final['country'].append(v['title'])
    final['code'] .append(v['code'])
    final['confirmed'].append(v['total_cases'])
    final['active'].append(v['total_active_cases'])
    final['recovered'].append(v['total_recovered'])
    final['deaths'].append(v['total_deaths'])
    final['cases_today'].append(v['total_new_cases_today'])
    final['deaths_today'].append(v['total_new_deaths_today'])
    final['serious'].append(v['total_serious_cases'])

In [19]:
final

{'country': ['Afghanistan',
  'Albania',
  'Algeria',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo',
  'Democratic Republic of Congo',
  'Costa Rica',
  'Ivory Coast',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Greenland',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Korea',
  'South Korea',
  'Kuwait',
  'Kyrgyzstan',
  'Lao',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Mali',
  'Mauritania',
  'Mexico',
  'Moldova',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of Kosovo',
  'Romania',
  'Rwanda',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Sierra Leone',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Kingdom',
  'USA',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Singapore',
  'Hong Kong',
  'DR Congo',
  'Kosovo',
  'Diamond Princess',
  'Iran',
  'North Korea',
  'Russia',
  'UAE',
  'Vietnam'],
 'code': ['AF',
  'AL',
  'DZ',
  'AO',
  'AR',
  'AM',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BD',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BT',
  'BO',
  'BA',
  'BW',
  'BR',
  'BN',
  'BG',
  'BF',
  'BI',
  'KH',
  'CM',
  'CA',
  'CF',
  'TD',
  'CL',
  'CN',
  'CO',
  'CG',
  'CD',
  'CR',
  'CI',
  'HR',
  'CU',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FK',
  'FJ',
  'FI',
  'FR',
  'GF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GR',
  'GL',
  'GT',
  'GN',
  'GW',
  'GY',
  'HT',
  'HN',
  'HU',
  'IS',
  'IN',
  'ID',
  'IQ',
  'IE',
  'IL',
  'IT',
  'JM',
  'JP',
  'JO',
  'KZ',
  'KE',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LT',
  'LU',
  'MK',
  'MG',
  'MW',
  'MY',
  'ML',
  'MR',
  'MX',
  'MD',
  'MN',
  'ME',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NO',
  'OM',
  'PK',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'PR',
  'QA',
  'XK',
  'RO',
  'RW',
  'SA',
  'SN',
  'RS',
  'SL',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SZ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TT',
  'TN',
  'TR',
  'TM',
  'UG',
  'UA',
  'GB',
  'US',
  'UY',
  'UZ',
  'VU',
  'VE',
  'EH',
  'YE',
  'ZM',
  'ZW',
  'SG',
  'HK',
  'CD',
  'XK',
  'DP',
  'IR',
  'KP',
  'RU',
  'AE',
  'VN'],
 'confirmed': [3563,
  842,
  4997,
  36,
  5208,
  2884,
  6896,
  15752,
  2127,
  92,
  12425,
  19255,
  51420,
  18,
  140,
  7,
  1886,
  2027,
  23,
  126611,
  141,
  1811,
  729,
  15,
  122,
  2267,
  63496,
  1,
  170,
  23048,
  82885,
  8959,
  264,
  0,
  761,
  1516,
  2119,
  1703,
  883,
  7979,
  10083,
  1124,
  8807,
  29420,
  7588,
  695,
  439,
  39,
  1720,
  187,
  13,
  18,
  5673,
  174191,
  138,
  0,
  439,
  17,
  615,
  168276,
  3091,
  2663,
  11,
  798,
  1856,
  475,
  93,
  108,
  1461,
  3150,
  1799,
  53045,
  12776,
  2480,
  22248,
  16346,
  214457,
  478,
  15253,
  473,
  4509,
  582,
  0,
  6593,
  6289,
  895,
  0,
  909,
  784,
  0,
  178,
  64,
  1433,
  3851,
  1539,
  158,
  43,
  6467,
  631,
  8,
  27634,
  4476,
  41,
  324,
  5505,
  81,
  162,
  16,
  99,
  41774,
  18,
  1489,
  16,
  770,
  3145,
  7996,
  2958,
  24073,
  374,
  7731,
  8,
  440,
  54817,
  10343,
  14898,
  26182,
  39,
  18890,
  0,
  14499,
  268,
  31938,
  1492,
  9791,
  225,
  1445,
  1449,
  0,
  873,
  7808,
  58,
  256855,
  797,
  852,
  10,
  0,
  0,
  24623,
  30126,
  0,
  440,
  379,
  480,
  2992,
  24,
  128,
  116,
  1025,
  131744,
  0,
  100,
  13691,
  201101,
  1263243,
  673,
  2266,
  0,
  379,
  6,
  25,
  146,
  34,
  20939,
  1045,
  0,
  0,
  712,
  103135,
  0,
  177160,
  16240,
  288],
 'active': [2989,
  206,
  2324,
  23,
  3411,
  1657,
  759,
  1445,
  563,
  55,
  10329,
  14755,
  30025,
  2,
  85,
  2,
  1597,
  983,
  14,
  66653,
  9,
  1343,
  126,
  7,
  2,
  1157,
  31093,
  0,
  110,
  11578,
  295,
  6414,
  224,
  0,
  327,
  777,
  433,
  633,
  572,
  3502,
  2084,
  366,
  6485,
  24369,
  5304,
  435,
  422,
  9,
  1391,
  90,
  2,
  4,
  1918,
  94410,
  25,
  0,
  332,
  7,
  331,
  21099,
  2770,
  1142,
  1,
  691,
  1248,
  449,
  56,
  81,
  1230,
  1966,
  39,
  35927,
  9465,
  776,
  3763,
  5370,
  91528,
  412,
  10201,
  87,
  3029,
  366,
  0,
  0,
  4028,
  246,
  0,
  427,
  539,
  0,
  83,
  37,
  645,
  301,
  394,
  57,
  31,
  1584,
  338,
  1,
  7149,
  2584,
  28,
  51,
  3198,
  60,
  106,
  7,
  77,
  36236,
  1,
  136,
  4,
  171,
  2508,
  7748,
  1964,
  17045,
  198,
  6654,
  2,
  288,
  35757,
  8040,
  9299,
  23017,
  36,
  16592,
  0,
  7479,
  138,
  24946,
  917,
  7617,
  157,
  613,
  1103,
  0,
  747,
  4502,
  58,
  66866,
  556,
  723,
  1,
  0,
  0,
  17509,
  2621,
  0,
  87,
  371,
  297,
  165,
  4,
  42,
  5,
  391,
  49958,
  0,
  45,
  10955,
  170681,
  975324,
  170,
  664,
  0,
  193,
  1,
  19,
  41,
  25,
  19285,
  97,
  0,
  0,
  54,
  13905,
  0,
  151732,
  12503,
  55],
 'recovered': [468,
  605,
  2197,
  11,
  1524,
  1185,
  6040,
  13698,
  1536,
  26,
  1910,
  4388,
  12980,
  14,
  53,
  5,
  198,
  954,
  8,
  51370,
  131,
  384,
  555,
  7,
  120,
  1002,
  28171,
  0,
  43,
  11189,
  77957,
  2148,
  30,
  0,
  428,
  721,
  1601,
  1001,
  296,
  4214,
  7493,
  755,
  1960,
  3433,
  1815,
  245,
  13,
  30,
  273,
  93,
  11,
  14,
  3500,
  53972,
  112,
  0,
  99,
  9,
  275,
  139900,
  303,
  1374,
  10,
  86,
  597,
  24,
  27,
  15,
  132,
  801,
  1750,
  15331,
  2381,
  1602,
  17110,
  10737,
  93245,
  57,
  4496,
  377,
  1450,
  190,
  0,
  135,
  2219,
  637,
  0,
  464,
  220,
  0,
  75,
  24,
  739,
  3452,
  1057,
  101,
  9,
  4776,
  261,
  6,
  17781,
  1747,
  13,
  265,
  2124,
  21,
  50,
  9,
  22,
  0,
  17,
  1332,
  7,
  561,
  534,
  32,
  980,
  6464,
  174,
  859,
  6,
  142,
  17527,
  1618,
  4862,
  2076,
  1,
  2286,
  0,
  6144,
  130,
  6783,
  562,
  1971,
  54,
  806,
  247,
  0,
  87,
  3153,
  0,
  163919,
  232,
  80,
  8,
  0,
  0,
  4074,
  25700,
  0,
  347,
  0,
  167,
  2772,
  20,
  77,
  103,
  591,
  78202,
  0,
  55,
  2396,
  0,
  213109,
  486,
  1592,
  0,
  176,
  5,
  1,
  101,
  5,
  1634,
  944,
  0,
  0,
  645,
  82744,
  0,
  23803,
  3572,
  233],
 'deaths': [106,
  31,
  476,
  2,
  273,
  42,
  97,
  609,
  28,
  11,
  186,
  112,
  8415,
  2,
  2,
  0,
  91,
  90,
  1,
  8588,
  1,
  84,
  48,
  1,
  0,
  108,
  4232,
  0,
  17,
  281,
  4633,
  397,
  10,
  0,
  6,
  18,
  85,
  69,
  15,
  263,
  506,
  3,
  362,
  1618,
  469,
  15,
  4,
  0,
  56,
  4,
  0,
  0,
  255,
  25809,
  1,
  0,
  8,
  1,
  9,
  7277,
  18,
  147,
  0,
  21,
  11,
  2,
  10,
  12,
  99,
  383,
  10,
  1787,
  930,
  102,
  1375,
  239,
  29684,
  9,
  556,
  9,
  30,
  26,
  0,
  42,
  42,
  12,
  0,
  18,
  25,
  0,
  20,
  3,
  49,
  98,
  88,
  0,
  3,
  107,
  32,
  1,
  2704,
  145,
  0,
  8,
  183,
  0,
  6,
  0,
  0,
  5288,
  0,
  21,
  5,
  38,
  103,
  216,
  14,
  564,
  2,
  218,
  0,
  10,
  1533,
  685,
  737,
  1089,
  2,
  12,
  0,
  876,
  0,
  209,
  13,
  203,
  14,
  26,
  99,
  0,
  39,
  153,
  0,
  26070,
  9,
  49,
  1,
  0,
  0,
  3040,
  1805,
  0,
  6,
  8,
  16,
  55,
  0,
  9,
  8,
  43,
  3584,
  0,
  0,
  340,
  30076,
  74810,
  17,
  10,
  0,
  10,
  0,
  5,
  4,
  4,
  20,
  4,
  0,
  0,
  13,
  6486,
  0,
  1625,
  165,
  0],
 'cases_today': [171,
  10,
  0,
  0,
  0,
  102,
  21,
  68,
  0,
  0,
  706,
  0,
  639,
  0,
  44,
  0,
  84,
  40,
  0,
  0,
  2,
  33,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  145,
  0,
  0,
  0,
  0,
  62,
  0,
  0,
  7,
  25,
  0,
  0,
  100,
  0,
  0,
  0,
  42,
  0,
  5,
  114,
  0,
  0,
  0,
  35,
  0,
  0,
  0,
  7,
  191,
  39,
  0,
  58,
  338,
  0,
  0,
  36,
  0,
  5,
  0,
  0,
  87,
  0,
  0,
  0,
  0,
  24,
  0,
  9,
  34,
  0,
  0,
  0,
  5,
  0,
  0,
  0,
  0,
  39,
  0,
  0,
  1609,
  0,
  0,
  0,
  97,
  0,
  1,
  0,
  0,
  455,
  0,
  1,
  0,
  0,
  0,
  0,
  55,
  859,
  0,
  208,
  0,
  0,
  0,
  339,
  158,
  0,
  0,
  918,
  0,
  392,
  0,
  0,
  59,
  0,
  0,
  16,
  1,
  0,
  0,
  0,
  0,
  3173,
  0,
  0,
  0,
  0,
  0,
  705,
  66,
  0,
  1,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  507,
  0,
  151,
  0,
  33,
  0,
  0,
  0,
  0,
  0,
  0,
  741,
  4,
  0,
  0,
  0,
  1485,
  0,
  11231,
  502,
  17],
 'deaths_today': [2,
  0,
  0,
  0,
  0,
  2,
  0,
  1,
  0,
  0,
  0,
  0,
  76,
  0,
  0,
  0,
  5,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  2,
  0,
  0,
  2,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  6,
  10,
  0,
  2,
  35,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  197,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  84,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  20,
  0,
  8,
  0,
  0,
  0,
  27,
  4,
  0,
  0,
  0,
  0,
  12,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  213,
  0,
  0,
  0,
  0,
  0,
  99,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  13,
  0,
  11,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  68,
  0,
  88,
  8,
  0],
 'serious': [7,
  7,
  22,
  0,
  148,
  10,
  23,
  92,
  18,
  1,
  1,
  92,
  538,
  1,
  0,
  0,
  3,
  4,
  0,
  8318,
  2,
  38,
  0,
  0,
  1,
  12,
  502,
  0,
  0,
  470,
  23,
  123,
  0,
  0,
  5,
  0,
  14,
  14,
  15,
  52,
  46,
  0,
  144,
  156,
  0,
  4,
  0,
  0,
  4,
  1,
  0,
  0,
  44,
  3147,
  0,
  0,
  1,
  0,
  6,
  1884,
  4,
  36,
  0,
  5,
  0,
  0,
  3,
  0,
  10,
  50,
  0,
  0,
  0,
  0,
  93,
  83,
  1333,
  0,
  308,
  5,
  31,
  1,
  0,
  0,
  88,
  13,
  0,
  3,
  43,
  0,
  0,
  0,
  17,
  20,
  21,
  1,
  1,
  19,
  0,
  0,
  378,
  237,
  0,
  2,
  1,
  0,
  0,
  0,
  0,
  628,
  1,
  2,
  0,
  0,
  4,
  27,
  17,
  111,
  0,
  88,
  0,
  9,
  717,
  31,
  160,
  136,
  0,
  72,
  0,
  234,
  0,
  137,
  6,
  48,
  0,
  4,
  13,
  0,
  2,
  36,
  0,
  2075,
  1,
  0,
  0,
  0,
  0,
  425,
  121,
  0,
  0,
  0,
  7,
  61,
  0,
  0,
  0,
  18,
  1278,
  0,
  0,
  178,
  1559,
  15827,
  10,
  8,
  0,
  1,
  0,
  0,
  1,
  0,
  23,
  1,
  0,
  0,
  4,
  2728,
  0,
  2300,
  1,
  8]}

In [20]:
pd.DataFrame(final)

,country,code,confirmed,active,recovered,deaths,cases_today,deaths_today,serious
0,Afghanistan,AF,3563,2989,468,106,171,2,7
1,Albania,AL,842,206,605,31,10,0,7
2,Algeria,DZ,4997,2324,2197,476,0,0,22
3,Angola,AO,36,23,11,2,0,0,0
4,Argentina,AR,5208,3411,1524,273,0,0,148
5,Armenia,AM,2884,1657,1185,42,102,2,10
6,Australia,AU,6896,759,6040,97,21,0,23
7,Austria,AT,15752,1445,13698,609,68,1,92
8,Azerbaijan,AZ,2127,563,1536,28,0,0,18
9,Bahamas,BS,92,55,26,11,0,0,1
10,Bangladesh,BD,12425,10329,1910,186,706,0,1
11,Belarus,BY,19255,14755,4388,112,0,0,92
12,Belgium,BE,51420,30025,12980,8415,639,76,538
13,Belize,BZ,18,2,14,2,0,0,1
14,Benin,BJ,140,85,53,2,44,0,0
15,Bhutan,BT,7,2,5,0,0,0,0
16,Bolivia,BO,1886,1597,198,91,84,5,3
17,Bosnia and Herzegovina,BA,2027,983,954,90,40,4,4
18,Botswana,BW,23,14,8,1,0,0,0
19,Brazil,BR,126611,66653,51370,8588,0,0,8318
20,Brunei Darussalam,BN,141,9,131,1,2,0,2
21,Bulgaria,BG,1811,1343,384,84,33,0,38
22,Burkina Faso,BF,729,126,555,48,0,0,0
23,Burundi,BI,15,7,7,1,0,0,0
24,Cambodia,KH,122,2,120,0,0,0,1
25,Cameroon,CM,2267,1157,1002,108,2,0,12
26,Canada,CA,63496,31093,28171,4232,0,0,502
27,Central African Republic,CF,1,0,0,0,0,0,0
28,Chad,TD,170,110,43,17,0,0,0
29,Chile,CL,23048,11578,11189,281,0,0,470
30,China,CN,82885,295,77957,4633,2,0,23
31,Colombia,CO,8959,6414,2148,397,0,0,123
32,Congo,CG,264,224,30,10,0,0,0
33,Democratic Republic of Congo,CD,0,0,0,0,0,0,0
34,Costa Rica,CR,761,327,428,6,0,0,5
35,Ivory Coast,CI,1516,777,721,18,0,0,0
36,Croatia,HR,2119,433,1601,85,0,0,14
37,Cuba,CU,1703,633,1001,69,0,0,14
38,Cyprus,CY,883,572,296,15,0,0,15
39,Czechia,CZ,7979,3502,4214,263,5,1,52
40,Denmark,DK,10083,2084,7493,506,145,0,46
41,Djibouti,DJ,1124,366,755,3,0,0,0
42,Dominican Republic,DO,8807,6485,1960,362,0,0,144
43,Ecuador,EC,29420,24369,3433,1618,0,0,156
44,Egypt,EG,7588,5304,1815,469,0,0,0
45,El Salvador,SV,695,435,245,15,62,0,4
46,Equatorial Guinea,GQ,439,422,13,4,0,0,0
47,Eritrea,ER,39,9,30,0,0,0,0
48,Estonia,EE,1720,1391,273,56,7,1,4
49,Ethiopia,ET,187,90,93,4,25,0,1
50,Falkland Islands,FK,13,2,11,0,0,0,0
51,Fiji,FJ,18,4,14,0,0,0,0
52,Finland,FI,5673,1918,3500,255,100,3,44
53,France,FR,174191,94410,53972,25809,0,0,3147
54,French Guiana,GF,138,25,112,1,0,0,0
55,French Southern Territories,TF,0,0,0,0,0,0,0
56,Gabon,GA,439,332,99,8,42,2,1
57,Gambia,GM,17,7,9,1,0,0,0
58,Georgia,GE,615,331,275,9,5,0,6
59,Germany,DE,168276,21099,139900,7277,114,2,1884
60,Ghana,GH,3091,2770,303,18,0,0,4
61,Greece,GR,2663,1142,1374,147,0,0,36
62,Greenland,GL,11,1,10,0,0,0,0
63,Guatemala,GT,798,691,86,21,35,2,5
64,Guinea,GN,1856,1248,597,11,0,0,0
65,Guinea-Bissau,GW,475,449,24,2,0,0,0
66,Guyana,GY,93,56,27,10,0,0,3
67,Haiti,HT,108,81,15,12,7,0,0
68,Honduras,HN,1461,1230,132,99,191,6,10
69,Hungary,HU,3150,1966,801,383,39,10,50
70,Iceland,IS,1799,39,1750,10,0,0,0
71,India,IN,53045,35927,15331,1787,58,2,0
72,Indonesia,ID,12776,9465,2381,930,338,35,0
73,Iraq,IQ,2480,776,1602,102,0,0,0
74,Ireland,IE,22248,3763,17110,1375,0,0,93
75,Israel,IL,16346,5370,10737,239,36,0,83
76,Italy,IT,214457,91528,93245,29684,0,0,1333
77,Jamaica,JM,478,412,57,9,5,0,0
78,Japan,JP,15253,10201,4496,556,0,0,308
79,Jordan,JO,473,87,377,9,0,0,5
80,Kazakhstan,KZ,4509,3029,1450,30,87,0,31
81,Kenya,KE,582,366,190,26,0,0,1
82,Korea,KP,0,0,0,0,0,0,0
83,South Korea,KR,6593,0,135,42,0,0,0
84,Kuwait,KW,6289,4028,2219,42,0,0,88
85,Kyrgyzstan,KG,895,246,637,12,24,0,13
86,Lao,LA,0,0,0,0,0,0,0
87,Latvia,LV,909,427,464,18,9,1,3
88,Lebanon,LB,784,539,220,25,34,0,43
89,Lesotho,LS,0,0,0,0,0,0,0
90,Liberia,LR,178,83,75,20,0,0,0
91,Libya,LY,64,37,24,3,0,0,0
92,Lithuania,LT,1433,645,739,49,5,1,17
93,Luxembourg,LU,3851,301,3452,98,0,0,20
94,Macedonia,MK,1539,394,1057,88,0,0,21
95,Madagascar,MG,158,57,101,0,0,0,1
96,Malawi,MW,43,31,9,3,0,0,1
97,Malaysia,MY,6467,1584,4776,107,39,0,19
98,Mali,ML,631,338,261,32,0,0,0
99,Mauritania,MR,8,1,6,1,0,0,0
100,Mexico,MX,27634,7149,17781,2704,1609,197,378
101,Moldova,MD,4476,2584,1747,145,0,2,237
102,Mongolia,MN,41,28,13,0,0,0,0
103,Montenegro,ME,324,51,265,8,0,0,2
104,Morocco,MA,5505,3198,2124,183,97,0,1
105,Mozambique,MZ,81,60,21,0,0,0,0
106,Myanmar,MM,162,106,50,6,1,0,0
107,Namibia,NA,16,7,9,0,0,0,0
108,Nepal,NP,99,77,22,0,0,0,0
109,Netherlands,NL,41774,36236,0,5288,455,84,628
110,New Caledonia,NC,18,1,17,0,0,0,1
111,New Zealand,NZ,1489,136,1332,21,1,0,2
112,Nicaragua,NI,16,4,7,5,0,0,0
113,Niger,NE,770,171,561,38,0,0,0
114,Nigeria,NG,3145,2508,534,103,0,0,4
115,Norway,NO,7996,7748,32,216,0,0,27
116,Oman,OM,2958,1964,980,14,55,1,17
117,Pakistan,PK,24073,17045,6464,564,859,20,111
118,Palestine,PS,374,198,174,2,0,0,0
119,Panama,PA,7731,6654,859,218,208,8,88
120,Papua New Guinea,PG,8,2,6,0,0,0,0
121,Paraguay,PY,440,288,142,10,0,0,9
122,Peru,PE,54817,35757,17527,1533,0,0,717
123,Philippines,PH,10343,8040,1618,685,339,27,31
124,Poland,PL,14898,9299,4862,737,158,4,160
125,Portugal,PT,26182,23017,2076,1089,0,0,136
126,Puerto Rico,PR,39,36,1,2,0,0,0
127,Qatar,QA,18890,16592,2286,12,918,0,72
128,Republic of Kosovo,XK,0,0,0,0,0,0,0
129,Romania,RO,14499,7479,6144,876,392,12,234
130,Rwanda,RW,268,138,130,0,0,0,0
131,Saudi Arabia,SA,31938,24946,6783,209,0,0,137
132,Senegal,SN,1492,917,562,13,59,1,6
133,Serbia,RS,9791,7617,1971,203,0,0,48
134,Sierra Leone,SL,225,157,54,14,0,0,0
135,Slovakia,SK,1445,613,806,26,16,1,4
136,Slovenia,SI,1449,1103,247,99,1,0,13
137,Solomon Islands,SB,0,0,0,0,0,0,0
138,Somalia,SO,873,747,87,39,0,0,2
139,South Africa,ZA,7808,4502,3153,153,0,0,36
140,South Sudan,SS,58,58,0,0,0,0,0
141,Spain,ES,256855,66866,163919,26070,3173,213,2075
142,Sri Lanka,LK,797,556,232,9,0,0,1
143,Sudan,SD,852,723,80,49,0,0,0
144,Suriname,SR,10,1,8,1,0,0,0
145,Svalbard and Jan Mayen,SJ,0,0,0,0,0,0,0
146,Swaziland,SZ,0,0,0,0,0,0,0
147,Sweden,SE,24623,17509,4074,3040,705,99,425
148,Switzerland,CH,30126,2621,25700,1805,66,0,121
149,Syrian Arab Republic,SY,0,0,0,0,0,0,0
150,Taiwan,TW,440,87,347,6,1,0,0
151,Tajikistan,TJ,379,371,0,8,0,0,0
152,Tanzania,TZ,480,297,167,16,0,0,7
153,Thailand,TH,2992,165,2772,55,3,0,61
154,Timor-Leste,TL,24,4,20,0,0,0,0
155,Togo,TG,128,42,77,9,0,0,0
156,Trinidad and Tobago,TT,116,5,103,8,0,0,0
157,Tunisia,TN,1025,391,591,43,0,0,18
158,Turkey,TR,131744,49958,78202,3584,0,0,1278
159,Turkmenistan,TM,0,0,0,0,0,0,0
160,Uganda,UG,100,45,55,0,0,0,0
161,Ukraine,UA,13691,10955,2396,340,507,13,178
162,United Kingdom,GB,201101,170681,0,30076,0,0,1559
163,USA,US,1263243,975324,213109,74810,151,11,15827
164,Uruguay,UY,673,170,486,17,0,0,10
165,Uzbekistan,UZ,2266,664,1592,10,33,0,8
166,Vanuatu,VU,0,0,0,0,0,0,0
167,Venezuela,VE,379,193,176,10,0,0,1
168,Western Sahara,EH,6,1,5,0,0,0,0
169,Yemen,YE,25,19,1,5,0,0,0
170,Zambia,ZM,146,41,101,4,0,0,1
171,Zimbabwe,ZW,34,25,5,4,0,0,0
172,Singapore,SG,20939,19285,1634,20,741,0,23
173,Hong Kong,HK,1045,97,944,4,4,0,1
174,DR Congo,CD,0,0,0,0,0,0,0
175,Kosovo,XK,0,0,0,0,0,0,0
176,Diamond Princess,DP,712,54,645,13,0,0,4
177,Iran,IR,103135,13905,82744,6486,1485,68,2728
178,North Korea,KP,0,0,0,0,0,0,0
179,Russia,RU,177160,151732,23803,1625,11231,88,2300
180,UAE,AE,16240,12503,3572,165,502,8,1
181,Vietnam,VN,288,55,233,0,17,0,8

'ok'